services:
  video-ingestor:
    build:
      context: .
      dockerfile: ./video_ingest/Dockerfile
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
    image: video-ingestor:latest
    hostname: video-ingestor
    container_name: video-ingestor
    ports:
      - "9005:9005"
    environment:
      - VECTORDB_SERVICE_HOST_IP=${VECTORDB_SERVICE_HOST_IP:-10.67.127.18}
      - CHOICE_OF_DB=${CHOICE_OF_DB:-vdms}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./video_ingest/videos:/video_ingest/videos:ro"
      - "./video_ingest/scene_description:/video_ingest/scene_description:ro"
      # - "./video_ingest/:/video_ingest" # development

  user-interface:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
    image: user-interface:latest
    hostname: user-interface
    container_name: user-interface
    ports:
      - "50055:50055"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - VECTORDB_SERVICE_HOST_IP=${VECTORDB_SERVICE_HOST_IP:-10.67.127.18}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./video_ingest/videos:/video_ingest/videos:ro"
      - "./video_ingest/scene_description:/video_ingest/scene_description:ro"
      - "/$USER/.cache/huggingface:/root/.cache/huggingface"